_target_: evaluators.SingleRequestEvaluator
bidirectional: True
_num_examples: null

eval_kwargs:
  model: gpt-4o-mini
  n: 1
  temperature: 0
  top_p: 1
  response_format: { "type": "json_object" }

prompt_filepath: configs/prompts/evaluation/single_request.txt
